# Generated by Django 5.1.13 on 2025-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_tag_article_multimedia_article_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('none', 'Без мультимедіа'), ('image', 'Фото'), ('video', 'Відео (YouTube/Vimeo)')], default='none', max_length=10, verbose_name='Тип мультимедіа'),
        ),
        migrations.AddField(
            model_name='article',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='articles_media/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='article',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на відео'),
        ),
    ]
