# Generated by Django 5.1.13 on 2025-10-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_content_type_article_media_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('none', 'Без мультимедіа'), ('image', 'Фото'), ('video', 'Відео (YouTube/Vimeo)')], default='none', max_length=10, verbose_name='Мультимедіа'),
        ),
        migrations.AlterField(
            model_name='article',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='Відео (YouTube/Vimeo)'),
        ),
    ]
